#use_frameworks!

platform :ios, '9.0'

target 'WFPaymentComponent_Example' do
  pod 'WFPaymentComponent', :path => '../'

  target 'WFPaymentComponent_Tests' do
    inherit! :search_paths

    
  end
end
